name: coverage
on: [push]
env:
  SECRET_KEY: ${{ vars.SECRET_KEY }}
  EMAIL_HOST_USER: ${{ vars.EMAIL_HOST_USER }}
  EMAIL_HOST_PASSWORD: ${{ vars.EMAIL_HOST_PASSWORD }}
jobs:
  coverage:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Test coverage
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          retry_wait_seconds: 30
          timeout_minutes: 3
          command: ./scripts/coverage.sh
